// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// data2raster
CharacterMatrix data2raster(NumericMatrix x, CharacterVector col, NumericVector colorder, NumericVector usr, int width, int height, int cex, int ncores);
RcppExport SEXP _rasterPoints_data2raster(SEXP xSEXP, SEXP colSEXP, SEXP colorderSEXP, SEXP usrSEXP, SEXP widthSEXP, SEXP heightSEXP, SEXP cexSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type col(colSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type colorder(colorderSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type usr(usrSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    Rcpp::traits::input_parameter< int >::type cex(cexSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(data2raster(x, col, colorder, usr, width, height, cex, ncores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rasterPoints_data2raster", (DL_FUNC) &_rasterPoints_data2raster, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_rasterPoints(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
