// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// data2raster
IntegerMatrix data2raster(const NumericMatrix& x, const IntegerVector& col_idx, const IntegerVector& colorder, NumericVector usr, int width, int height, const IntegerVector cex, int ncores);
RcppExport SEXP _rasterPoints_data2raster(SEXP xSEXP, SEXP col_idxSEXP, SEXP colorderSEXP, SEXP usrSEXP, SEXP widthSEXP, SEXP heightSEXP, SEXP cexSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type col_idx(col_idxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type colorder(colorderSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type usr(usrSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type cex(cexSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(data2raster(x, col_idx, colorder, usr, width, height, cex, ncores));
    return rcpp_result_gen;
END_RCPP
}
// data2raster_density
IntegerMatrix data2raster_density(const NumericMatrix& x, NumericVector usr, int width, int height, int n_bins, bool smooth, int smooth_radius, double smooth_sigma, double margin_pct, double cex, int ncores);
RcppExport SEXP _rasterPoints_data2raster_density(SEXP xSEXP, SEXP usrSEXP, SEXP widthSEXP, SEXP heightSEXP, SEXP n_binsSEXP, SEXP smoothSEXP, SEXP smooth_radiusSEXP, SEXP smooth_sigmaSEXP, SEXP margin_pctSEXP, SEXP cexSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type usr(usrSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    Rcpp::traits::input_parameter< int >::type n_bins(n_binsSEXP);
    Rcpp::traits::input_parameter< bool >::type smooth(smoothSEXP);
    Rcpp::traits::input_parameter< int >::type smooth_radius(smooth_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type smooth_sigma(smooth_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type margin_pct(margin_pctSEXP);
    Rcpp::traits::input_parameter< double >::type cex(cexSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(data2raster_density(x, usr, width, height, n_bins, smooth, smooth_radius, smooth_sigma, margin_pct, cex, ncores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rasterPoints_data2raster", (DL_FUNC) &_rasterPoints_data2raster, 8},
    {"_rasterPoints_data2raster_density", (DL_FUNC) &_rasterPoints_data2raster_density, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_rasterPoints(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
