# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' data2raster
#' 
#' This function convert a 2 column matrix of data in a img matrix.
#'
#' @param x Data matrix (ncol = 2).
#' @param colv An character vector with color codes with length = nrow(x).
#' @param colorder Integer 0=random color order, 1=ordered colors
#' @param usr An double vector. See par("usr").
#' @param width An integer.
#' @param height An integer.
#' @param cex An integer.
#' @param ncores Number of cores to use. Default to 0 (use max OpenMP avaiable cores).
data2raster <- function(x, colv, colorder, usr, width, height, cex = 1L, ncores = 0L) {
    .Call('_rasterPoints_data2raster', PACKAGE = 'rasterPoints', x, colv, colorder, usr, width, height, cex, ncores)
}

