# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' data2raster
#' 
#' This function convert a 2 column matrix of data in a img matrix.
#'
#' @param x Data matrix (ncol = 2).
#' @param col_idx Integer vector with color indices (1-based from R). With length = nrow(x).
#' @param colorder Numeric vector where index is color_id and value is priority.
#' @param usr An double vector. See par("usr").
#' @param width Output raster width.
#' @param height Output raster height.
#' @param cex Point size vector.
#' @param ncores Number of cores to use. Default to 0 (use max OpenMP avaiable cores).
data2raster <- function(x, col_idx, colorder, usr, width, height, cex, ncores = 0L) {
    .Call('_rasterPoints_data2raster', PACKAGE = 'rasterPoints', x, col_idx, colorder, usr, width, height, cex, ncores)
}

#' data2raster_density
#'
#' High-performance density aggregation for large scale flow cytometry data.
#' This function uses a binning approach (Datashader-style) instead of KDE
#' to achieve near-instant rendering of millions of events.
#'
#' @param x NumericMatrix with 2 columns (fluorescence channels).
#' @param usr NumericVector with plot limits c(x1, x2, y1, y2).
#' @param width Integer, output image width in pixels.
#' @param height Integer, output image height in pixels.
#' @param n_bins Integer, number of color steps (e.g., 256).
#' @param ncores Integer, number of OpenMP threads.
data2raster_density <- function(x, usr, width, height, n_bins = 256L, ncores = 0L) {
    .Call('_rasterPoints_data2raster_density', PACKAGE = 'rasterPoints', x, usr, width, height, n_bins, ncores)
}

